version: "3.1"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybatis
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    ports:
      - 3306:3306
